openapi: 3.0.3
info:
  title: Kanvas
  version: 1.0.0
  description: Entrega Final
paths:
  /api/accounts/:
    post:
      operationId: api_accounts_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Account'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
          description: ''
  /api/courses/:
    get:
      operationId: api_courses_list
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
          description: ''
    post:
      operationId: api_courses_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Course'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
          description: ''
  /api/courses/{course_id}/:
    get:
      operationId: api_courses_retrieve
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
          description: ''
    put:
      operationId: api_courses_update
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Course'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
          description: ''
    patch:
      operationId: api_courses_partial_update
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCourse'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCourse'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCourse'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
          description: ''
    delete:
      operationId: api_courses_destroy
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/courses/{course_id}/contents/:
    post:
      operationId: api_courses_contents_create
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Content'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Content'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Content'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
          description: ''
  /api/courses/{course_id}/contents/{content_id}/:
    get:
      operationId: api_courses_contents_retrieve
      parameters:
      - in: path
        name: content_id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
          description: ''
    put:
      operationId: api_courses_contents_update
      parameters:
      - in: path
        name: content_id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Content'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Content'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Content'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
          description: ''
    patch:
      operationId: api_courses_contents_partial_update
      parameters:
      - in: path
        name: content_id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedContent'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedContent'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedContent'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
          description: ''
    delete:
      operationId: api_courses_contents_destroy
      parameters:
      - in: path
        name: content_id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/courses/{course_id}/students/:
    get:
      operationId: api_courses_students_retrieve
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentTest'
          description: ''
    put:
      operationId: api_courses_students_update
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentTest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/StudentTest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/StudentTest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentTest'
          description: ''
    patch:
      operationId: api_courses_students_partial_update
      parameters:
      - in: path
        name: course_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedStudentTest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedStudentTest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedStudentTest'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentTest'
          description: ''
  /api/login/:
    post:
      operationId: api_login_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        password:
          type: string
          writeOnly: true
          maxLength: 128
        email:
          type: string
          maxLength: 100
        is_superuser:
          type: boolean
          title: Superuser status
          description: Designates that this user has all permissions without explicitly
            assigning them.
      required:
      - email
      - id
      - password
      - username
    Content:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 150
        content:
          type: string
        video_url:
          type: string
          nullable: true
          maxLength: 200
      required:
      - content
      - id
      - name
    Course:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 100
        status:
          $ref: '#/components/schemas/CourseStatusEnum'
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        instructor:
          type: string
          format: uuid
          nullable: true
        students_courses:
          type: array
          items:
            type: string
            format: uuid
          readOnly: true
        contents:
          type: array
          items:
            type: string
            format: uuid
          readOnly: true
      required:
      - contents
      - end_date
      - id
      - name
      - start_date
      - students_courses
    CourseStatusEnum:
      enum:
      - not started
      - in progress
      - finished
      type: string
      description: |-
        * `not started` - Not Started
        * `in progress` - In Progress
        * `finished` - Finished
    PatchedContent:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 150
        content:
          type: string
        video_url:
          type: string
          nullable: true
          maxLength: 200
    PatchedCourse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 100
        status:
          $ref: '#/components/schemas/CourseStatusEnum'
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        instructor:
          type: string
          format: uuid
          nullable: true
        students_courses:
          type: array
          items:
            type: string
            format: uuid
          readOnly: true
        contents:
          type: array
          items:
            type: string
            format: uuid
          readOnly: true
    PatchedStudentTest:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          readOnly: true
        students_courses:
          type: array
          items:
            $ref: '#/components/schemas/StudentCourse'
    StudentCourse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        student_username:
          type: string
          readOnly: true
        student_email:
          type: string
        status:
          $ref: '#/components/schemas/StudentCourseStatusEnum'
        student_id:
          type: string
          format: uuid
          readOnly: true
      required:
      - id
      - student_email
      - student_id
      - student_username
    StudentCourseStatusEnum:
      enum:
      - pending
      - accepted
      type: string
      description: |-
        * `pending` - Pending
        * `accepted` - Accepted
    StudentTest:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          readOnly: true
        students_courses:
          type: array
          items:
            $ref: '#/components/schemas/StudentCourse'
      required:
      - id
      - name
      - students_courses
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
