# Generated by Django 5.0.6 on 2024-05-21 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_instructor'),
        ('students_courses', '0002_alter_studentcourse_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='estudante', through='students_courses.StudentCourse', to=settings.AUTH_USER_MODEL),
        ),
    ]
